server:
  port: 8080

# application.yml 文件中的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/check_in
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      lettuce:
        pool:
          max-active: 8
          max-idle: 6
          min-idle: 0
          max-wait: 1000

mybatis:
  # 配置 Mapper 文件的路径
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 配置 MyBatis 的配置属性
  configuration:
    # 是否打印 SQL 语句
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    # 是否开启缓存
    cacheEnabled: true
    # 是否开启延迟加载
    lazyLoadingEnabled: true
    # 延迟加载策略
    aggressiveLazyLoading: true
    # 是否开启列别名
    useColumnLabel: true
    # 是否开启驼峰命名映射
    mapUnderscoreToCamelCase: true

email:
  host: smtp.qq.com
  from: 851891179@qq.com
  user: Mark
  passcode: ktyfuelwoypibcfc
